# Understanding-containers pipeline based on a main build task

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - bash: |
          sudo apt install libcap-dev -y
        displayName: installing libcap-dev
      - bash: |
          sudo apt install libseccomp-dev -y
        displayName: installing libseccomp-dev
      - bash: |
          sudo apt install iptables-dev -y
        displayName: installing iptables-dev
      - bash: |
          pwd
          mkdir build
          cd build
          cmake ..
          make -j $(getconf _NPROCESSORS_ONLN)
        displayName: build