# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

#pool:
#  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: |
      pwd
      mkdir build
      cd build
      cmake ..
      make -j $(getconf _NPROCESSORS_ONLN)

#  - task: CMake@1
#    inputs:
#      workingDirectory: 'build'
#      cmakeArgs: '..'
#  - bash: make -j $(getconf _NPROCESSORS_ONLN)
  
    

#steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'

